# This workflow will do a clean installation of node dependencies, cache/restore them,
# lint, build the source code, and run tests across different versions of node.

# For more information see:
# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  workflow_dispatch:
  push:
    branches: ['main']
    paths-ignore: ['README.md', 'LICENSE']
  pull_request:
    branches: ['main']
    paths-ignore: ['README.md', 'LICENSE']

concurrency:
  group: ci-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  VITEST_SEGFAULT_RETRY: 3

jobs:
  ci-on-node:
    runs-on: ubuntu-latest

    timeout-minutes: 10

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install
        run: npm install

      - name: Lint
        run: npm run lint --if-present

      - name: Build
        run: npm run build --if-present

      - name: Test
        run: npm run test-run --if-present
